apiVersion: v1
kind: Service
metadata:
  name: django-notes-service
  namespace: learndev
  labels:
    app: django-notes
spec:
  type: ClusterIP
  selector:
    app: django-notes
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
