apiVersion: v1
kind: Service
metadata:
  name: django-notes-service
  namespace: learndev
  labels:
    app: django-notes
spec:
  type: NodePort
  selector:
    app: django-notes
  ports:
  - name: http
    port: 80
    targetPort: 8000
    nodePort: 30007
    protocol: TCP
