apiVersion: v1
kind: Service
metadata:
  name: django-notes-service
  namespace: learndev
spec:
  type: ClusterIP # change this
  selector:
    app: django-notes
  ports:
  - port: 80
    targetPort: 8000
